export type UnitType = 'length' | 'weight' | 'area' | 'volume' | 'temperature' | 'time' | 'data' | 'speed' | 'energy' | 'pressure' | 'power' | 'angle' | 'frequency' | 'force' | 'torque' | 'illuminance' | 'volumetricFlow' | 'fuelConsumption' | 'viscosity' | 'digitalRate' | 'current' | 'voltage' | 'luminousIntensity' | 'magnetism' | 'radiation' | 'currency' | 'crypto';

export interface UnitDefinition {
  label: string;
  value: string;
  factor: number; // Factor relative to base unit
  offset?: number; // For non-linear like temperature
}

export const unitsMap: Record<UnitType, UnitDefinition[]> = {
  length: [
    { label: 'Meter (m)', value: 'm', factor: 1 },
    { label: 'Kilometer (km)', value: 'km', factor: 1000 },
    { label: 'Centimeter (cm)', value: 'cm', factor: 0.01 },
    { label: 'Millimeter (mm)', value: 'mm', factor: 0.001 },
    { label: 'Micrometer (μm)', value: 'um', factor: 1e-6 },
    { label: 'Nanometer (nm)', value: 'nm', factor: 1e-9 },
    { label: 'Picometer (pm)', value: 'pm', factor: 1e-12 },
    { label: 'Femtometer (fm)', value: 'fm', factor: 1e-15 },
    { label: 'Angstrom (Å)', value: 'angstrom', factor: 1e-10 },
    { label: 'Decimeter (dm)', value: 'dm', factor: 0.1 },
    { label: 'Decameter (dam)', value: 'dam', factor: 10 },
    { label: 'Hectometer (hm)', value: 'hm', factor: 100 },
    { label: 'Megameter (Mm)', value: 'mm_large', factor: 1e6 },
    { label: 'Gigameter (Gm)', value: 'gm_large', factor: 1e9 },
    { label: 'Mile (mi)', value: 'mi', factor: 1609.344 },
    { label: 'Yard (yd)', value: 'yd', factor: 0.9144 },
    { label: 'Foot (ft)', value: 'ft', factor: 0.3048 },
    { label: 'Inch (in)', value: 'in', factor: 0.0254 },
    { label: 'Mil / Thou (mil)', value: 'mil', factor: 0.0000254 },
    { label: 'Microinch (μin)', value: 'uin', factor: 2.54e-8 },
    { label: 'Nautical Mile (nmi)', value: 'nmi', factor: 1852 },
    { label: 'Furlong (fur)', value: 'furlong', factor: 201.168 },
    { label: 'Chain (ch)', value: 'chain', factor: 20.1168 },
    { label: 'Link (li)', value: 'li', factor: 0.201168 },
    { label: 'Fathom (fath)', value: 'fathom', factor: 1.8288 },
    { label: 'Hand (hand)', value: 'hand', factor: 0.1016 },
    { label: 'Point (pt)', value: 'pt', factor: 0.000352777778 },
    { label: 'Pica (pica)', value: 'pica', factor: 0.00423333333 },
    { label: 'Light Year (ly)', value: 'ly', factor: 9.4607304725808e15 },
    { label: 'Parsec (pc)', value: 'pc', factor: 3.085677581e16 },
    { label: 'Astronomical Unit (AU)', value: 'au', factor: 1.495978707e11 },
    { label: 'Planck Length (ℓP)', value: 'planck', factor: 1.616255e-35 },
  ],
  weight: [
    { label: 'Kilogram (kg)', value: 'kg', factor: 1 },
    { label: 'Gram (g)', value: 'g', factor: 0.001 },
    { label: 'Milligram (mg)', value: 'mg', factor: 1e-6 },
    { label: 'Microgram (μg)', value: 'ug', factor: 1e-9 },
    { label: 'Nanogram (ng)', value: 'ng', factor: 1e-12 },
    { label: 'Picogram (pg)', value: 'pg', factor: 1e-15 },
    { label: 'Femtogram (fg)', value: 'fg', factor: 1e-18 },
    { label: 'Dalton / Atomic Mass (Da/u)', value: 'da', factor: 1.6605390666e-27 },
    { label: 'Tonne (t)', value: 't', factor: 1000 },
    { label: 'Pound (lb)', value: 'lb', factor: 0.45359237 },
    { label: 'Ounce (oz)', value: 'oz', factor: 0.0283495231 },
    { label: 'Stone (st)', value: 'st', factor: 6.35029318 },
    { label: 'Carat (ct)', value: 'ct', factor: 0.0002 },
    { label: 'Slug (slug)', value: 'slug', factor: 14.593903 },
    { label: 'Grain (gr)', value: 'grain', factor: 6.479891e-5 },
    { label: 'Dram (dr)', value: 'dram', factor: 0.001771845 },
    { label: 'Troy Ounce (ozt)', value: 'ozt', factor: 0.0311034768 },
    { label: 'Pennyweight (dwt)', value: 'dwt', factor: 0.00155517384 },
    { label: 'Quintal (q)', value: 'quintal', factor: 100 },
    { label: 'Ton (US / Short)', value: 'ton_us', factor: 907.18474 },
    { label: 'Ton (UK / Long)', value: 'ton_uk', factor: 1016.0469 },
    { label: 'Quarter (US)', value: 'quarter_us', factor: 11.33980925 },
    { label: 'Hundredweight (US / Short cwt)', value: 'cwt_us', factor: 45.359237 },
    { label: 'Hundredweight (UK / Long cwt)', value: 'cwt_uk', factor: 50.802345 },
  ],
  area: [
    { label: 'Square Meter (m²)', value: 'm2', factor: 1 },
    { label: 'Square Kilometer (km²)', value: 'km2', factor: 1e6 },
    { label: 'Square Centimeter (cm²)', value: 'cm2', factor: 0.0001 },
    { label: 'Square Millimeter (mm²)', value: 'mm2', factor: 1e-6 },
    { label: 'Square Decimeter (dm²)', value: 'dm2', factor: 0.01 },
    { label: 'Square Micrometer (μm²)', value: 'um2', factor: 1e-12 },
    { label: 'Square Nanometer (nm²)', value: 'nm2', factor: 1e-18 },
    { label: 'Square Mile (mi²)', value: 'mi2', factor: 2589988.11 },
    { label: 'Square Yard (yd²)', value: 'yd2', factor: 0.83612736 },
    { label: 'Square Foot (ft²)', value: 'ft2', factor: 0.09290304 },
    { label: 'Square Inch (in²)', value: 'in2', factor: 0.00064516 },
    { label: 'Acre (ac)', value: 'ac', factor: 4046.85642 },
    { label: 'Hectare (ha)', value: 'ha', factor: 10000 },
    { label: 'Are (a)', value: 'are', factor: 100 },
    { label: 'Barn (b)', value: 'barn', factor: 1e-28 },
    { label: 'Square Rod (rd²)', value: 'rd2', factor: 25.29285 },
    { label: 'Square Chain (ch²)', value: 'ch2', factor: 404.68564 },
    { label: 'Rood', value: 'rood', factor: 1011.714 },
    { label: 'Circular Mil (cmil)', value: 'cmil', factor: 5.067075e-10 },
    { label: 'Township (twp)', value: 'twp', factor: 9.323957e7 },
    { label: 'Homestead', value: 'homestead', factor: 647497 },
  ],
  volume: [
    { label: 'Liter (L)', value: 'l', factor: 1 },
    { label: 'Milliliter (ml)', value: 'ml', factor: 0.001 },
    { label: 'Microliter (μL)', value: 'ul', factor: 1e-6 },
    { label: 'Nanoliter (nL)', value: 'nl', factor: 1e-9 },
    { label: 'Picoliter (pL)', value: 'pl', factor: 1e-12 },
    { label: 'Cubic Meter (m³)', value: 'm3', factor: 1000 },
    { label: 'Cubic Centimeter (cm³ / cc)', value: 'cm3', factor: 0.001 },
    { label: 'Cubic Millimeter (mm³)', value: 'mm3', factor: 1e-6 },
    { label: 'Hectoliter (hl)', value: 'hl', factor: 100 },
    { label: 'Deciliter (dl)', value: 'dl', factor: 0.1 },
    { label: 'Centiliter (cl)', value: 'cl', factor: 0.01 },
    { label: 'Cubic Foot (ft³)', value: 'ft3', factor: 28.3168466 },
    { label: 'Cubic Inch (in³)', value: 'in3', factor: 0.016387064 },
    { label: 'Gallon (US)', value: 'gal', factor: 3.78541178 },
    { label: 'Gallon (UK)', value: 'gal_uk', factor: 4.54609 },
    { label: 'Quart (US)', value: 'qt', factor: 0.946352946 },
    { label: 'Quart (UK)', value: 'qt_uk', factor: 1.1365225 },
    { label: 'Pint (US)', value: 'pt', factor: 0.473176473 },
    { label: 'Pint (UK)', value: 'pt_uk', factor: 0.56826125 },
    { label: 'Cup (US)', value: 'cup', factor: 0.24 },
    { label: 'Fluid Ounce (US)', value: 'floz', factor: 0.0295735296 },
    { label: 'Fluid Ounce (UK)', value: 'floz_uk', factor: 0.0284130625 },
    { label: 'Tablespoon (US)', value: 'tbsp', factor: 0.01478676 },
    { label: 'Teaspoon (US)', value: 'tsp', factor: 0.00492892 },
    { label: 'Barrel (Oil)', value: 'bbl', factor: 158.9873 },
    { label: 'Barrel (US Liquid)', value: 'bbl_us', factor: 119.24 },
    { label: 'Gill (US)', value: 'gill_us', factor: 0.118294118 },
    { label: 'Gill (UK)', value: 'gill_uk', factor: 0.142065312 },
    { label: 'Minim (US)', value: 'minim_us', factor: 6.161152e-5 },
    { label: 'Fluid Dram (US fl dr)', value: 'fldram_us', factor: 0.003696691 },
    { label: 'Board Foot', value: 'board_foot', factor: 0.002359737 },
    { label: 'Acre-Foot', value: 'acre_foot', factor: 1233481.84 },
    { label: 'Cord (wood)', value: 'cord', factor: 3624.556 },
  ],
  temperature: [
    { label: 'Celsius (°C)', value: 'c', factor: 1, offset: 0 },
    { label: 'Fahrenheit (°F)', value: 'f', factor: 1.8, offset: 32 },
    { label: 'Kelvin (K)', value: 'k', factor: 1, offset: 273.15 },
    { label: 'Rankine (°R)', value: 'r', factor: 1.8, offset: 491.67 },
    { label: 'Réaumur (°Ré)', value: 're', factor: 0.8, offset: 0 },
    { label: 'Delisle (°De)', value: 'de_temp', factor: 1, offset: 0 },
    { label: 'Newton (°N)', value: 'n_temp', factor: 1, offset: 0 },
    { label: 'Rømer (°Rø)', value: 'ro_temp', factor: 1, offset: 0 },
  ],
  time: [
    { label: 'Second (s)', value: 's', factor: 1 },
    { label: 'Millisecond (ms)', value: 'ms', factor: 0.001 },
    { label: 'Microsecond (μs)', value: 'us', factor: 1e-6 },
    { label: 'Nanosecond (ns)', value: 'ns', factor: 1e-9 },
    { label: 'Picosecond (ps)', value: 'ps', factor: 1e-12 },
    { label: 'Femtosecond (fs)', value: 'fs', factor: 1e-15 },
    { label: 'Minute (min)', value: 'min', factor: 60 },
    { label: 'Hour (h)', value: 'h', factor: 3600 },
    { label: 'Day (d)', value: 'd', factor: 86400 },
    { label: 'Week (wk)', value: 'wk', factor: 604800 },
    { label: 'Fortnight', value: 'fortnight', factor: 1209600 },
    { label: 'Month (avg)', value: 'mo', factor: 2629746 },
    { label: 'Year (avg)', value: 'yr', factor: 31556952 },
    { label: 'Decade', value: 'decade', factor: 315569520 },
    { label: 'Century', value: 'century', factor: 3155695200 },
    { label: 'Millennium', value: 'millennium', factor: 31556952000 },
    { label: 'Planck Time', value: 'planck_time', factor: 5.391247e-44 },
    { label: 'Svedberg (S)', value: 'svedberg', factor: 1e-13 },
    { label: 'Shake', value: 'shake', factor: 1e-8 },
    { label: 'Martian Sol (sol)', value: 'sol', factor: 88775.244 },
  ],
  data: [
    { label: 'Byte (B)', value: 'b', factor: 1 },
    { label: 'Bit (bit)', value: 'bit', factor: 0.125 },
    { label: 'Nibble', value: 'nibble', factor: 0.5 },
    { label: 'Kilobit (Kb)', value: 'kbit', factor: 128 },
    { label: 'Megabit (Mb)', value: 'mbit', factor: 128 * 1024 },
    { label: 'Gigabit (Gb)', value: 'gbit', factor: 128 * (1024 ** 2) },
    { label: 'Terabit (Tb)', value: 'tbit', factor: 128 * (1024 ** 3) },
    { label: 'Kilobyte (KB)', value: 'kb', factor: 1024 },
    { label: 'Megabyte (MB)', value: 'mb', factor: 1024 ** 2 },
    { label: 'Gigabyte (GB)', value: 'gb', factor: 1024 ** 3 },
    { label: 'Terabyte (TB)', value: 'tb', factor: 1024 ** 4 },
    { label: 'Petabyte (PB)', value: 'pb', factor: 1024 ** 5 },
    { label: 'Exabyte (EB)', value: 'eb', factor: 1024 ** 6 },
    { label: 'Zettabyte (ZB)', value: 'zb', factor: 1024 ** 7 },
    { label: 'Yottabyte (YB)', value: 'yb', factor: 1024 ** 8 },
    { label: 'Brontobyte', value: 'brontobyte', factor: 1024 ** 9 },
    { label: 'Geopbyte', value: 'geopbyte', factor: 1024 ** 10 },
    { label: 'Kibibyte (KiB)', value: 'kib', factor: 1024 },
    { label: 'Mebibyte (MiB)', value: 'mib', factor: 1024 ** 2 },
    { label: 'Gibibyte (GiB)', value: 'gib', factor: 1024 ** 3 },
    { label: 'Tebibyte (TiB)', value: 'tib', factor: 1024 ** 4 },
    { label: 'Pebibyte (PiB)', value: 'pib', factor: 1024 ** 5 },
    { label: '3.5" HD Floppy (1.44MB)', value: 'floppy', factor: 1474560 },
    { label: 'CD-ROM (700MB)', value: 'cdrom', factor: 734003200 },
    { label: 'DVD-5 (4.7GB)', value: 'dvd', factor: 4700000000 },
  ],
  speed: [
    { label: 'Meters/sec (m/s)', value: 'ms', factor: 1 },
    { label: 'Kilometers/hour (km/h)', value: 'kmh', factor: 1 / 3.6 },
    { label: 'Kilometers/second (km/s)', value: 'kms', factor: 1000 },
    { label: 'Kilometers/minute (km/min)', value: 'kmmin', factor: 16.66667 },
    { label: 'Millimeter/second (mm/s)', value: 'mms', factor: 0.001 },
    { label: 'Miles/hour (mph)', value: 'mph', factor: 0.44704 },
    { label: 'Miles/second (mi/s)', value: 'mps_sec', factor: 1609.344 },
    { label: 'Miles/minute (mi/min)', value: 'mipmin', factor: 26.8224 },
    { label: 'Feet/sec (fps)', value: 'fps', factor: 0.3048 },
    { label: 'Yards/minute (ypm)', value: 'ypm', factor: 0.01524 },
    { label: 'Knot (kn)', value: 'kn', factor: 0.51444444 },
    { label: 'Knot (UK) (adm)', value: 'kn_uk', factor: 0.51477 },
    { label: 'Mach (at STP)', value: 'mach', factor: 340.29 },
    { label: 'Speed of Sound in Air (343 m/s)', value: 'sound_air', factor: 343 },
    { label: 'Speed of Light (c)', value: 'c_speed', factor: 299792458 },
  ],
  energy: [
    { label: 'Joule (J)', value: 'j', factor: 1 },
    { label: 'Kilojoule (kJ)', value: 'kj', factor: 1000 },
    { label: 'Megajoule (MJ)', value: 'mj', factor: 1e6 },
    { label: 'Gigajoule (GJ)', value: 'gj', factor: 1e9 },
    { label: 'Calorie (cal)', value: 'cal', factor: 4.184 },
    { label: 'Kilocalorie (kcal)', value: 'kcal', factor: 4184 },
    { label: 'Watt-hour (Wh)', value: 'wh', factor: 3600 },
    { label: 'Kilowatt-hour (kWh)', value: 'kwh', factor: 3.6e6 },
    { label: 'Megawatt-hour (MWh)', value: 'mwh', factor: 3.6e9 },
    { label: 'Gigawatt-hour (GWh)', value: 'gwh', factor: 3.6e12 },
    { label: 'Electronvolt (eV)', value: 'ev', factor: 1.602176634e-19 },
    { label: 'British Thermal Unit (BTU)', value: 'btu', factor: 1055.05585 },
    { label: 'Erg (erg)', value: 'erg', factor: 1e-7 },
    { label: 'Foot-pound-force (ft·lbf)', value: 'ftlbf', factor: 1.355818 },
    { label: 'Therm (US)', value: 'therm', factor: 1.054804e8 },
    { label: 'Ton of TNT (tTNT)', value: 'tnt', factor: 4.184e9 },
    { label: 'Hartree (atomic unit)', value: 'hartree', factor: 4.359744722e-18 },
    { label: 'Rydberg (Ry)', value: 'rydberg', factor: 2.179872e-18 },
    { label: 'Quad', value: 'quad', factor: 1.05505585e18 },
  ],
  pressure: [
    { label: 'Pascal (Pa)', value: 'pa', factor: 1 },
    { label: 'Kilopascal (kPa)', value: 'kpa', factor: 1000 },
    { label: 'Megapascal (MPa)', value: 'mpa', factor: 1e6 },
    { label: 'Gigapascal (GPa)', value: 'gpa', factor: 1e9 },
    { label: 'Hectopascal (hPa)', value: 'hpa', factor: 100 },
    { label: 'Bar', value: 'bar', factor: 1e5 },
    { label: 'Millibar (mbar)', value: 'mbar', factor: 100 },
    { label: 'Atmosphere (atm)', value: 'atm', factor: 101325 },
    { label: 'Technical Atmosphere (at)', value: 'at_pres', factor: 98066.5 },
    { label: 'PSI (lbf/in²)', value: 'psi', factor: 6894.75729 },
    { label: 'Torr', value: 'torr', factor: 133.322368 },
    { label: 'Millimeter of Mercury (mmHg)', value: 'mmhg', factor: 133.322387 },
    { label: 'Inch of Mercury (inHg)', value: 'inhg', factor: 3386.389 },
    { label: 'Barye (Ba)', value: 'barye', factor: 0.1 },
    { label: 'Millimeter of Water (mmH₂O)', value: 'mmh2o', factor: 9.80665 },
    { label: 'Inch of Water (inH₂O)', value: 'inh2o', factor: 249.0889 },
  ],
  power: [
    { label: 'Watt (W)', value: 'w', factor: 1 },
    { label: 'Milliwatt (mW)', value: 'mw_small', factor: 0.001 },
    { label: 'Microwatt (μW)', value: 'uw_small', factor: 1e-6 },
    { label: 'Nanowatt (nW)', value: 'nw_small', factor: 1e-9 },
    { label: 'Kilowatt (kW)', value: 'kw', factor: 1000 },
    { label: 'Megawatt (MW)', value: 'mw', factor: 1e6 },
    { label: 'Gigawatt (GW)', value: 'gw', factor: 1e9 },
    { label: 'Horsepower (Mechanical/hp)', value: 'hp', factor: 745.699872 },
    { label: 'Horsepower (Metric)', value: 'hp_metric', factor: 735.49875 },
    { label: 'Horsepower (Electrical)', value: 'hp_elec', factor: 746 },
    { label: 'Horsepower (Boiler)', value: 'hp_boiler', factor: 9809.5 },
    { label: 'Calorie/second (cal/s)', value: 'cals', factor: 4.184 },
    { label: 'BTU/hour (BTU/hr)', value: 'btu_hr', factor: 0.29307107 },
    { label: 'Ton of Refrigeration (TR)', value: 'ton_refrig', factor: 3516.85284 },
  ],
  angle: [
    { label: 'Degree (°)', value: 'deg', factor: 1 },
    { label: 'Radian (rad)', value: 'rad', factor: 180 / Math.PI },
    { label: 'Gradient (grad)', value: 'grad', factor: 0.9 },
    { label: 'Arcminute', value: 'arcmin', factor: 1 / 60 },
    { label: 'Arcsecond', value: 'arcsec', factor: 1 / 3600 },
    { label: 'Turn / Revolution (tr)', value: 'turn', factor: 360 },
    { label: 'Quadrant', value: 'quadrant', factor: 90 },
    { label: 'Sextant', value: 'sextant', factor: 60 },
    { label: 'NATO Mil (mil)', value: 'mil_nato', factor: 360 / 6400 },
    { label: 'Sign (Zodiac)', value: 'sign', factor: 30 },
    { label: 'Octant', value: 'octant', factor: 45 },
  ],
  frequency: [
    { label: 'Hertz (Hz)', value: 'hz', factor: 1 },
    { label: 'Millihertz (mHz)', value: 'mhz_small', factor: 0.001 },
    { label: 'Kilohertz (kHz)', value: 'khz', factor: 1000 },
    { label: 'Megahertz (MHz)', value: 'mhz', factor: 1e6 },
    { label: 'Gigahertz (GHz)', value: 'ghz', factor: 1e9 },
    { label: 'Terahertz (THz)', value: 'thz', factor: 1e12 },
    { label: 'Decahertz (daHz)', value: 'dahz', factor: 10 },
    { label: 'Hectohertz (hHz)', value: 'hhz', factor: 100 },
    { label: 'Petahertz (PHz)', value: 'phz', factor: 1e15 },
    { label: 'Exahertz (EHz)', value: 'ehz', factor: 1e18 },
    { label: 'RPM (revs/min)', value: 'rpm', factor: 1 / 60 },
    { label: 'Radian/second (rad/s)', value: 'rads', factor: 1 / (2 * Math.PI) },
    { label: 'BPM (Beats per minute)', value: 'bpm', factor: 1 / 60 },
  ],
  force: [
    { label: 'Newton (N)', value: 'n', factor: 1 },
    { label: 'Kilonewton (kN)', value: 'kn', factor: 1000 },
    { label: 'Millinewton (mN)', value: 'mn', factor: 0.001 },
    { label: 'Micronewton (μN)', value: 'un_force', factor: 1e-6 },
    { label: 'Pound-force (lbf)', value: 'lbf', factor: 4.44822162 },
    { label: 'Kilogram-force (kgf)', value: 'kgf', factor: 9.80665 },
    { label: 'Gram-force (gf)', value: 'gf', factor: 0.00980665 },
    { label: 'Dyne (dyn)', value: 'dyn', factor: 1e-5 },
    { label: 'Kip (kip)', value: 'kip', factor: 4448.2216 },
    { label: 'Poundal (pdl)', value: 'pdl', factor: 0.138255 },
    { label: 'Short Ton-force (tonf_us)', value: 'tonf_us', factor: 8896.44323 },
    { label: 'Long Ton-force (tonf_uk)', value: 'tonf_uk', factor: 9964.016412 },
    { label: 'Metric Ton-force (tf)', value: 'tf', factor: 9806.65 },
  ],
  torque: [
    { label: 'Newton-meter (N·m)', value: 'nm', factor: 1 },
    { label: 'Newton-centimeter (N·cm)', value: 'ncm', factor: 0.01 },
    { label: 'Pound-foot (lb·ft)', value: 'lbft', factor: 1.35581795 },
    { label: 'Pound-inch (lb·in)', value: 'lbin', factor: 0.112984829 },
    { label: 'Ounce-inch (oz·in)', value: 'ozin', factor: 0.00706155 },
    { label: 'Kilogram-meter (kg·m)', value: 'kgm', factor: 9.80665 },
    { label: 'Kilogram-centimeter (kg·cm)', value: 'kgcm', factor: 0.0980665 },
    { label: 'Dyn-centimeter (dyn·cm)', value: 'dyncm', factor: 1e-7 },
    { label: 'Kilonewton-meter (kN·m)', value: 'knm', factor: 1000 },
    { label: 'Meganewton-meter (MN·m)', value: 'mnm', factor: 1e6 },
  ],
  illuminance: [
    { label: 'Lux (lx)', value: 'lx', factor: 1 },
    { label: 'Foot-candle (fc)', value: 'fc', factor: 10.7639104 },
    { label: 'Phot (ph)', value: 'ph', factor: 10000 },
    { label: 'Nox (nx)', value: 'nx', factor: 0.001 },
    { label: 'Lumen/sq. meter (lm/m²)', value: 'lmm2', factor: 1 },
    { label: 'Lumen/sq. centimeter (lm/cm²)', value: 'lmcm2', factor: 10000 },
    { label: 'Lumen/sq. millimeter (lm/mm²)', value: 'lmmm2', factor: 1e6 },
    { label: 'Microlux (μlx)', value: 'ulx', factor: 1e-6 },
  ],
  volumetricFlow: [
    { label: 'm³/second (m³/s)', value: 'm3s', factor: 1 },
    { label: 'm³/hour (m³/h)', value: 'm3h', factor: 1 / 3600 },
    { label: 'm³/day (m³/d)', value: 'm3d', factor: 1 / 86400 },
    { label: 'Cubic feet/second (cfs)', value: 'cfs', factor: 0.028316846 },
    { label: 'Cubic Feet/min (cfm)', value: 'cfm', factor: 0.0004719474 },
    { label: 'Cubic inch/minute (cim)', value: 'cim', factor: 2.731177e-7 },
    { label: 'Liter/second (L/s)', value: 'ls', factor: 0.001 },
    { label: 'Liter/minute (L/min)', value: 'lm', factor: 0.001 / 60 },
    { label: 'Liter/hour (L/h)', value: 'lh', factor: 0.001 / 3600 },
    { label: 'Milliliter/second (mL/s)', value: 'mls', factor: 1e-6 },
    { label: 'Gallon/second (US gps)', value: 'gps', factor: 0.00378541178 },
    { label: 'Gallon/minute (US/gpm)', value: 'gpm', factor: 0.0000630902 },
    { label: 'Gallon/hour (US/gph)', value: 'gph', factor: 1.0515e-6 },
    { label: 'Acre-foot/day', value: 'afd', factor: 0.01427641 },
    { label: 'Barrel/day (bpd)', value: 'bpd', factor: 1.84013e-6 },
  ],
  fuelConsumption: [
    { label: 'Liter/100km (L/100km)', value: 'l100km', factor: 1 },
    { label: 'MPG (US)', value: 'mpg_us', factor: 235.214583 },
    { label: 'MPG (UK)', value: 'mpg_uk', factor: 282.480936 },
    { label: 'Kilometer/Liter (km/L)', value: 'kml', factor: 100 },
    { label: 'Liter/Kilometer (L/km)', value: 'l_km', factor: 100 },
    { label: 'Mile/Liter (mi/L)', value: 'mil_l', factor: 62.1371192 },
    { label: 'Gallon/100 miles (US)', value: 'g100m_us', factor: 2.35214583 },
    { label: 'Gallon/100 miles (UK)', value: 'g100m_uk', factor: 2.82480936 },
  ],
  viscosity: [
    { label: 'Pascal-second (Pa·s)', value: 'pas', factor: 1 },
    { label: 'Millipascal-second (mPa·s)', value: 'mpas', factor: 0.001 },
    { label: 'Poise (P)', value: 'p', factor: 0.1 },
    { label: 'Centipoise (cP)', value: 'cp', factor: 0.001 },
    { label: 'Reynord (reyn)', value: 'reyn', factor: 6894.757 },
    { label: 'KG/meter-second (kg/(m·s))', value: 'kgms', factor: 1 },
    { label: 'G/centimeter-second (g/(cm·s))', value: 'gcms', factor: 0.1 },
    { label: 'Lbf·second/sq. foot (lbf·s/ft²)', value: 'lbfs', factor: 47.880259 },
    { label: 'Lb/foot-second (lb/(ft·s))', value: 'lbfts_visc', factor: 1.488164 },
  ],
  digitalRate: [
    { label: 'bps (Bits/s)', value: 'bps', factor: 1 },
    { label: 'kbps (Kilobits/s)', value: 'kbps', factor: 1000 },
    { label: 'Mbps (Megabits/s)', value: 'mbps', factor: 1e6 },
    { label: 'Gbps (Gigabits/s)', value: 'gbps', factor: 1e9 },
    { label: 'Tbps (Terabits/s)', value: 'tbps', factor: 1e12 },
    { label: 'Pbps (Petabits/s)', value: 'pbps', factor: 1e15 },
    { label: 'Ebps (Exabits/s)', value: 'ebps', factor: 1e18 },
    { label: 'Bps (Bytes/s)', value: 'Bps', factor: 8 },
    { label: 'KBps (Kilobytes/s)', value: 'KBps', factor: 8000 },
    { label: 'MBps (Megabytes/s)', value: 'MBps', factor: 8e6 },
    { label: 'GBps (Gigabytes/s)', value: 'GBps', factor: 8e9 },
    { label: 'TBps (Terabytes/s)', value: 'TBps', factor: 8e12 },
    { label: 'PBps (Petabytes/s)', value: 'PBps_byte', factor: 8e15 },
    { label: 'EBps (Exabytes/s)', value: 'EBps_byte', factor: 8e18 },
    { label: 'KiBps (Kibibytes/s)', value: 'KiBps', factor: 8192 },
    { label: 'MiBps (Mebibytes/s)', value: 'MiBps', factor: 8192 * 1024 },
    { label: 'GiBps (Gibibytes/s)', value: 'GiBps', factor: 8192 * (1024 ** 2) },
  ],
  current: [
    { label: 'Ampere (A)', value: 'a', factor: 1 },
    { label: 'Milliampere (mA)', value: 'ma', factor: 1e-3 },
    { label: 'Microampere (μA)', value: 'ua', factor: 1e-6 },
    { label: 'Nanoampere (nA)', value: 'na', factor: 1e-9 },
    { label: 'Picoampere (pA)', value: 'pa', factor: 1e-12 },
    { label: 'Kiloampere (kA)', value: 'ka', factor: 1000 },
    { label: 'Megaampere (MA)', value: 'ma_large', factor: 1e6 },
    { label: 'Gigaampere (GA)', value: 'ga_large', factor: 1e9 },
    { label: 'Abampere (abA)', value: 'aba', factor: 10 },
    { label: 'Biot (Bi)', value: 'bi', factor: 10 },
    { label: 'Statampere (statA)', value: 'stata', factor: 3.33564e-10 },
  ],
  voltage: [
    { label: 'Volt (V)', value: 'v', factor: 1 },
    { label: 'Millivolt (mV)', value: 'mv', factor: 1e-3 },
    { label: 'Microvolt (μV)', value: 'uv', factor: 1e-6 },
    { label: 'Nanovolt (nV)', value: 'nv', factor: 1e-9 },
    { label: 'Picovolt (pV)', value: 'pv', factor: 1e-12 },
    { label: 'Kilovolt (kV)', value: 'kv', factor: 1000 },
    { label: 'Megavolt (MV)', value: 'mv_large', factor: 1e6 },
    { label: 'Gigavolt (GV)', value: 'gv_large', factor: 1e9 },
    { label: 'Teravolt (TV)', value: 'tv_large', factor: 1e12 },
    { label: 'Abvolt (abV)', value: 'abv', factor: 1e-8 },
    { label: 'Statvolt (statV)', value: 'statv', factor: 299.792458 },
  ],
  luminousIntensity: [
    { label: 'Candela (cd)', value: 'cd', factor: 1 },
    { label: 'Millicandela (mcd)', value: 'mcd', factor: 0.001 },
    { label: 'Kilocandela (kcd)', value: 'kcd', factor: 1000 },
    { label: 'Hefnerkerze (HK)', value: 'hk', factor: 0.92 },
    { label: 'Violle (violle)', value: 'violle', factor: 20.17 },
    { label: 'Carcel (carcel)', value: 'carcel', factor: 9.6 },
    { label: 'Decimal Candle (bougie dec.)', value: 'decimal_candle', factor: 1 },
  ],
  magnetism: [
    { label: 'Tesla (T)', value: 't', factor: 1 },
    { label: 'Millitesla (mT)', value: 'mt', factor: 0.001 },
    { label: 'Microtesla (μT)', value: 'ut', factor: 1e-6 },
    { label: 'Nanotesla (nT)', value: 'nt', factor: 1e-9 },
    { label: 'Picotesla (pT)', value: 'pt_magnet', factor: 1e-12 },
    { label: 'Kilotesla (kT)', value: 'kt_magnet', factor: 1000 },
    { label: 'Megatesla (MT)', value: 'mt_magnet', factor: 1e6 },
    { label: 'Gauss (G)', value: 'g', factor: 1e-4 },
    { label: 'Gamma (γ)', value: 'gamma', factor: 1e-9 },
    { label: 'Maxwell (Mx/cm²)', value: 'maxwell', factor: 1e-4 },
  ],
  radiation: [
    { label: 'Sievert (Sv)', value: 'sv', factor: 1 },
    { label: 'Millisievert (mSv)', value: 'msv', factor: 1e-3 },
    { label: 'Microsievert (μSv)', value: 'usv', factor: 1e-6 },
    { label: 'Nanosievert (nSv)', value: 'nsv', factor: 1e-9 },
    { label: 'Gray (Gy)', value: 'gy', factor: 1 },
    { label: 'Milligray (mGy)', value: 'mgy', factor: 0.001 },
    { label: 'Microgray (μGy)', value: 'ugy', factor: 1e-6 },
    { label: 'Kilogray (kGy)', value: 'kgy', factor: 1000 },
    { label: 'Rad', value: 'rad_rad', factor: 0.01 },
    { label: 'Millirad (mrad)', value: 'mrad', factor: 1e-5 },
    { label: 'Rem (rem)', value: 'rem', factor: 0.01 },
    { label: 'Millirem (mrem)', value: 'mrem', factor: 1e-5 },
    { label: 'Microrem (μrem)', value: 'urem', factor: 1e-8 },
    { label: 'Roentgen (R)', value: 'roentgen', factor: 0.00933 },
    { label: 'Micro-roentgen (μR)', value: 'ur_roentgen', factor: 9.33e-9 },
  ],
  currency: [
    { label: 'US Dollar (USD)', value: 'usd', factor: 1 },
    { label: 'Euro (EUR)', value: 'eur', factor: 0.92 },
    { label: 'British Pound (GBP)', value: 'gbp', factor: 0.79 },
    { label: 'Japanese Yen (JPY)', value: 'jpy', factor: 156.2 },
    { label: 'Canadian Dollar (CAD)', value: 'cad', factor: 1.37 },
    { label: 'Australian Dollar (AUD)', value: 'aud', factor: 1.51 },
    { label: 'Swiss Franc (CHF)', value: 'chf', factor: 0.90 },
    { label: 'Chinese Yuan (CNY)', value: 'cny', factor: 7.25 },
    { label: 'Swedish Krona (SEK)', value: 'sek', factor: 10.45 },
    { label: 'New Zealand Dollar (NZD)', value: 'nzd', factor: 1.63 },
    { label: 'Indian Rupee (INR)', value: 'inr', factor: 83.5 },
    { label: 'Brazilian Real (BRL)', value: 'brl', factor: 5.35 },
    { label: 'Singapore Dollar (SGD)', value: 'sgd', factor: 1.35 },
    { label: 'Hong Kong Dollar (HKD)', value: 'hkd', factor: 7.81 },
    { label: 'Turkish Lira (TRY)', value: 'try', factor: 32.5 },
    { label: 'Mexican Peso (MXN)', value: 'mxn', factor: 18.5 },
    { label: 'Russian Ruble (RUB)', value: 'rub', factor: 89.1 },
    { label: 'South African Rand (ZAR)', value: 'zar', factor: 18.4 },
    { label: 'UAE Dirham (AED)', value: 'aed', factor: 3.67 },
    { label: 'Saudi Riyal (SAR)', value: 'sar', factor: 3.75 },
    { label: 'Korean Won (KRW)', value: 'krw', factor: 1380 },
    { label: 'Norwegian Krone (NOK)', value: 'nok', factor: 10.60 },
    { label: 'Danish Krone (DKK)', value: 'dkk', factor: 6.90 },
    { label: 'Polish Zloty (PLN)', value: 'pln', factor: 4.02 },
    { label: 'Thai Baht (THB)', value: 'thb', factor: 36.7 },
    { label: 'Indonesian Rupiah (IDR)', value: 'idr', factor: 16400 },
    { label: 'Malaysian Ringgit (MYR)', value: 'myr', factor: 4.71 },
    { label: 'Philippine Peso (PHP)', value: 'php', factor: 58.7 },
    { label: 'Taiwan Dollar (TWD)', value: 'twd', factor: 32.4 },
    { label: 'Vietnamese Dong (VND)', value: 'vnd', factor: 25400 },
    { label: 'Ukrainian Hryvnia (UAH)', value: 'uah', factor: 40.5 },
    { label: 'Argentine Peso (ARS)', value: 'ars', factor: 900 },
    { label: 'Colombian Peso (COP)', value: 'cop', factor: 4100 },
    { label: 'Chilean Peso (CLP)', value: 'clp', factor: 930 },
    { label: 'Peruvian Sol (PEN)', value: 'pen', factor: 3.8 },
    { label: 'Egyptian Pound (EGP)', value: 'egp', factor: 48 },
    { label: 'Nigerian Naira (NGN)', value: 'ngn', factor: 1500 },
    { label: 'Kenyan Shilling (KES)', value: 'kes', factor: 130 },
    { label: 'Moroccan Dirham (MAD)', value: 'mad', factor: 10 },
    { label: 'Algerian Dinar (DZD)', value: 'dzd', factor: 134 },
    { label: 'Tunisian Dinar (TND)', value: 'tnd', factor: 3.1 },
    { label: 'Qatari Riyal (QAR)', value: 'qar', factor: 3.64 },
    { label: 'Kuwaiti Dinar (KWD)', value: 'kwd', factor: 0.31 },
    { label: 'Bahraini Dinar (BHD)', value: 'bhd', factor: 0.38 },
    { label: 'Omani Rial (OMR)', value: 'omr', factor: 0.38 },
    { label: 'Jordanian Dinar (JOD)', value: 'jod', factor: 0.71 },
    { label: 'Iraqi Dinar (IQD)', value: 'iqd', factor: 1310 },
    { label: 'Lebanese Pound (LBP)', value: 'lbp', factor: 89500 },
    { label: 'Kazakhstani Tenge (KZT)', value: 'kzt', factor: 450 },
    { label: 'Pakistani Rupee (PKR)', value: 'pkr', factor: 278 },
    { label: 'Bangladeshi Taka (BDT)', value: 'bdt', factor: 117 },
    { label: 'Sri Lankan Rupee (LKR)', value: 'lkr', factor: 302 },
    { label: 'Nepalese Rupee (NPR)', value: 'npr', factor: 133 },
    { label: 'Hungarian Forint (HUF)', value: 'huf', factor: 365 },
    { label: 'Czech Koruna (CZK)', value: 'czk', factor: 23 },
    { label: 'Romanian Leu (RON)', value: 'ron', factor: 4.6 },
    { label: 'Bulgarian Lev (BGN)', value: 'bgn', factor: 1.8 },
    { label: 'Icelandic Krona (ISK)', value: 'isk', factor: 139 },
    { label: 'Costa Rican Colón (CRC)', value: 'crc', factor: 525 },
    { label: 'Dominican Peso (DOP)', value: 'dop', factor: 59 },
    { label: 'Guatemalan Quetzal (GTQ)', value: 'gtq', factor: 7.7 },
    { label: 'Honduran Lempira (HNL)', value: 'hnl', factor: 24.7 },
    { label: 'Nicaraguan Córdoba (NIO)', value: 'nio', factor: 36.7 },
    { label: 'Panamanian Balboa (PAB)', value: 'pab', factor: 1 },
    { label: 'Uruguayan Peso (UYU)', value: 'uyu', factor: 39 },
    { label: 'Paraguayan Guaraní (PYG)', value: 'pyg', factor: 7500 },
    { label: 'Bolivian Boliviano (BOB)', value: 'bob', factor: 6.9 },
    { label: 'Venezuelan Bolívar (VES)', value: 'ves', factor: 36.4 },
    { label: 'Jamaican Dollar (JMD)', value: 'jmd', factor: 155 },
    { label: 'Trinidad and Tobago Dollar (TTD)', value: 'ttd', factor: 6.8 },
    { label: 'East Caribbean Dollar (XCD)', value: 'xcd', factor: 2.7 },
    { label: 'Ghanaian Cedi (GHS)', value: 'ghs', factor: 15 },
    { label: 'Ethiopian Birr (ETB)', value: 'etb', factor: 57 },
    { label: 'Angolan Kwanza (AOA)', value: 'aoa', factor: 850 },
    { label: 'Tanzanian Shilling (TZS)', value: 'tzs', factor: 2600 },
    { label: 'Ugandan Shilling (UGX)', value: 'ugx', factor: 3750 },
    { label: 'CFA Franc BCEAO (XOF)', value: 'xof', factor: 600 },
    { label: 'CFA Franc BEAC (XAF)', value: 'xaf', factor: 600 },
    { label: 'CFP Franc (XPF)', value: 'xpf', factor: 110 },
    { label: 'Georgian Lari (GEL)', value: 'gel', factor: 2.7 },
    { label: 'Armenian Dram (AMD)', value: 'amd', factor: 388 },
    { label: 'Azerbaijani Manat (AZN)', value: 'azn', factor: 1.70 },
    { label: 'Uzbekistani Som (UZS)', value: 'uzs', factor: 12600 },
    { label: 'Mongolian Tögrög (MNT)', value: 'mnt', factor: 3400 },
    { label: 'Cambodian Riel (KHR)', value: 'khr', factor: 4100 },
    { label: 'Lao Kip (LAK)', value: 'lak', factor: 22000 },
    { label: 'Myanmar Kyat (MMK)', value: 'mmk', factor: 2100 },
    { label: 'Brunei Dollar (BND)', value: 'bnd', factor: 1.35 },
    { label: 'Macanese Pataca (MOP)', value: 'mop', factor: 8 },
    { label: 'Maldivian Rufiyaa (MVR)', value: 'mvr', factor: 15.4 },
    { label: 'Mauritian Rupee (MUR)', value: 'mur', factor: 46.5 },
    { label: 'Seychellois Rupee (SCR)', value: 'scr', factor: 13.5 },
    { label: 'Malagasy Ariary (MGA)', value: 'mga', factor: 4500 },
    { label: 'Zambian Kwacha (ZMW)', value: 'zmw', factor: 26 },
    { label: 'Cuban Peso (CUP)', value: 'cup', factor: 24 },
    { label: 'Serbian Dinar (RSD)', value: 'rsd', factor: 108 },
    { label: 'Bosnian Convertible Mark (BAM)', value: 'bam', factor: 1.8 },
    { label: 'Albanian Lek (ALL)', value: 'all', factor: 93 },
    { label: 'Macedonian Denar (MKD)', value: 'mkd', factor: 56 },
    { label: 'Papuan New Guinean Kina (PGK)', value: 'pgk', factor: 3.9 },
    { label: 'Fijian Dollar (FJD)', value: 'fjd', factor: 2.25 },
    { label: 'Solomon Islands Dollar (SBD)', value: 'sbd', factor: 8.5 },
    { label: 'Vanuatuan Vatu (VUV)', value: 'vuv', factor: 120 },
    { label: 'Samoan Tālā (WST)', value: 'wst', factor: 2.75 },
    { label: 'Tongan Paʻanga (TOP)', value: 'top', factor: 2.35 },
    { label: 'Libyan Dinar (LYD)', value: 'lyd', factor: 4.85 },
    { label: 'Sudanese Pound (SDG)', value: 'sdg', factor: 600 },
    { label: 'South Sudanese Pound (SSP)', value: 'ssp', factor: 130 },
    { label: 'Syrian Pound (SYP)', value: 'syp', factor: 13000 },
    { label: 'Yemeni Rial (YER)', value: 'yer', factor: 250 },
    { label: 'Mauritanian Ouguiya (MRU)', value: 'mru', factor: 39.5 },
    { label: 'Somali Shilling (SOS)', value: 'sos', factor: 570 },
    { label: 'Djibouti Franc (DJF)', value: 'djf', factor: 177.7 },
    { label: 'Eritrean Nakfa (ERN)', value: 'ern', factor: 15.0 },
    { label: 'Burundi Franc (BIF)', value: 'bif', factor: 2850 },
    { label: 'Rwandan Franc (RWF)', value: 'rwf', factor: 1310 },
    { label: 'Malawian Kwacha (MWK)', value: 'mwk', factor: 1730 },
    { label: 'Mozambican Metical (MZN)', value: 'mzn', factor: 63.8 },
    { label: 'Botswana Pula (BWP)', value: 'bwp', factor: 13.6 },
    { label: 'Namibian Dollar (NAD)', value: 'nad', factor: 18.4 },
    { label: 'Lesotho Loti (LSL)', value: 'lsl', factor: 18.4 },
    { label: 'Swazi Lilangeni (SZL)', value: 'szl', factor: 18.4 },
    { label: 'Guinea Franc (GNF)', value: 'gnf', factor: 8600 },
    { label: 'Sierra Leonean Leone (SLE)', value: 'sle', factor: 22.5 },
    { label: 'Liberian Dollar (LRD)', value: 'lrd', factor: 194 },
    { label: 'Gambian Dalasi (GMD)', value: 'gmd', factor: 68 },
    { label: 'Cape Verdean Escudo (CVE)', value: 'cve', factor: 102 },
    { label: 'São Tomé and Príncipe Dobra (STN)', value: 'stn', factor: 22.8 },
    { label: 'Afghan Afghani (AFN)', value: 'afn', factor: 70.8 },
    { label: 'Tajikistani Somoni (TJS)', value: 'tjs', factor: 10.7 },
    { label: 'Kyrgyzstani Som (KGS)', value: 'kgs', factor: 87.5 },
    { label: 'Turkmenistani Manat (TMT)', value: 'tmt', factor: 3.5 },
    { label: 'Belarusian Ruble (BYN)', value: 'byn', factor: 3.27 },
    { label: 'Moldovan Leu (MDL)', value: 'mdl', factor: 17.7 },
    { label: 'Gibraltar Pound (GIP)', value: 'gip', factor: 0.79 },
    { label: 'Falkland Islands Pound (FKP)', value: 'fkp', factor: 0.79 },
    { label: 'Saint Helena Pound (SHP)', value: 'shp', factor: 0.79 },
    { label: 'Bermudian Dollar (BMD)', value: 'bmd', factor: 1.0 },
    { label: 'Cayman Islands Dollar (KYD)', value: 'kyd', factor: 0.83 },
    { label: 'Bahamian Dollar (BSD)', value: 'bsd', factor: 1.0 },
    { label: 'Barbadian Dollar (BBD)', value: 'bbd', factor: 2.0 },
    { label: 'Belize Dollar (BZD)', value: 'bzd', factor: 2.0 },
    { label: 'Guyanese Dollar (GYD)', value: 'gyd', factor: 209 },
    { label: 'Surinamese Dollar (SRD)', value: 'srd', factor: 31.5 },
    { label: 'Netherlands Antillean Guilder (ANG)', value: 'ang', factor: 1.8 },
    { label: 'Aruban Florin (AWG)', value: 'awg', factor: 1.79 },
    { label: 'Haitian Gourde (HTG)', value: 'htg', factor: 132 },
    { label: 'Iranian Rial (IRR)', value: 'irr', factor: 42000 },
  ],
  crypto: [
    { label: 'Bitcoin (BTC)', value: 'bitcoin', factor: 1 },
    { label: 'Ethereum (ETH)', value: 'ethereum', factor: 18.5 },
    { label: 'Solana (SOL)', value: 'solana', factor: 420 },
    { label: 'Cardano (ADA)', value: 'cardano', factor: 142000 },
    { label: 'Ripple (XRP)', value: 'ripple', factor: 110000 },
    { label: 'Polkadot (DOT)', value: 'polkadot', factor: 10200 },
    { label: 'Dogecoin (DOGE)', value: 'dogecoin', factor: 460000 },
    { label: 'Litecoin (LTC)', value: 'litecoin', factor: 820 },
    { label: 'Binance Coin (BNB)', value: 'binancecoin', factor: 110 },
    { label: 'Avalanche (AVAX)', value: 'avalanche', factor: 2300 },
    { label: 'Chainlink (LINK)', value: 'chainlink', factor: 4300 },
    { label: 'Uniswap (UNI)', value: 'uni', factor: 120 },
    { label: 'Polygon (MATIC)', value: 'matic', factor: 2100 },
    { label: 'TRON (TRX)', value: 'trx', factor: 8300 },
    { label: 'Toncoin (TON)', value: 'ton', factor: 135 },
    { label: 'Cosmos (ATOM)', value: 'atom', factor: 120 },
    { label: 'Near Protocol (NEAR)', value: 'near', factor: 170 },
    { label: 'Stellar (XLM)', value: 'xlm', factor: 9520 },
    { label: 'Monero (XMR)', value: 'xmr', factor: 5.8 },
    { label: 'Bitcoin Cash (BCH)', value: 'bch', factor: 2.1 },
    { label: 'Ethereum Classic (ETC)', value: 'etc', factor: 410 },
    { label: 'Shiba Inu (SHIB)', value: 'shib', factor: 44000000 },
  ],
};

export function convert(value: number, from: string, to: string, type: UnitType): number {
  const units = unitsMap[type];
  const fromUnit = units.find(u => u.value === from);
  const toUnit = units.find(u => u.value === to);

  if (!fromUnit || !toUnit) return value;

  // Temperature special case
  if (type === 'temperature') {
    let baseValue = value; // In Celsius
    if (from === 'f') baseValue = (value - 32) / 1.8;
    if (from === 'k') baseValue = value - 273.15;
    if (from === 'r') baseValue = (value - 491.67) / 1.8;
    if (from === 're') baseValue = value * 1.25;
    if (from === 'de_temp') baseValue = 100 - (value / 1.5);
    if (from === 'n_temp') baseValue = value / 0.33;
    if (from === 'ro_temp') baseValue = (value - 7.5) * 40 / 21;

    if (to === 'c') return baseValue;
    if (to === 'f') return (baseValue * 1.8) + 32;
    if (to === 'k') return baseValue + 273.15;
    if (to === 'r') return (baseValue * 1.8) + 491.67;
    if (to === 're') return baseValue * 0.8;
    if (to === 'de_temp') return (100 - baseValue) * 1.5;
    if (to === 'n_temp') return baseValue * 0.33;
    if (to === 'ro_temp') return (baseValue * 21 / 40) + 7.5;
    return baseValue;
  }

  // Fuel Consumption special case (reciprocal)
  if (type === 'fuelConsumption') {
    if (from === to) return value;
    if (value === 0) return 0;
    
    // Convert current to L/100km (base)
    let base;
    if (from === 'l100km') base = value;
    else if (from === 'mpg_us') base = 235.214583 / value;
    else if (from === 'mpg_uk') base = 282.480936 / value;
    else if (from === 'kml') base = 100 / value;
    else if (from === 'l_km') base = value * 100;
    else if (from === 'mil_l') base = 62.1371192 / value;
    else if (from === 'g100m_us') base = value * 2.35214583;
    else if (from === 'g100m_uk') base = value * 2.82480936;
    else base = value;

    // Convert base to Target
    if (to === 'l100km') return base;
    if (to === 'mpg_us') return 235.214583 / base;
    if (to === 'mpg_uk') return 282.480936 / base;
    if (to === 'kml') return 100 / base;
    if (to === 'l_km') return base / 100;
    if (to === 'mil_l') return 62.1371192 / base;
    if (to === 'g100m_us') return base / 2.35214583;
    if (to === 'g100m_uk') return base / 2.82480936;
    return base;
  }

  // Linear conversion
  const baseValue = value * fromUnit.factor;
  return baseValue / toUnit.factor;
}

